/*
1. 조건 : 입양 시간 09:00 ~ 19:59, 시간대별  입양 건수
2. 컬럼 : DATETIME, COUNT(ANIMAL_ID)
3. 정렬 : 오름차순
*/
SELECT HOUR(DATETIME) AS HOUR
,      COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC